version: '3.9'

services:
  nginx:
    container_name: k3i-nginx
    image: nginx:1.23.4
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/cert:/etc/nginx/ssl
      - /var/www/k3i:/var/www/k3i
      - /var/www/study:/var/www/study
    depends_on:
      - php81
      - pgadmin
    networks:
      - app-network
  
  php81:
    container_name: k3i-php81
    build: ./config/php81
    volumes:
      - /var/www/k3i:/var/www/k3i
      - /var/www/study:/var/www/study
    networks:
      - app-network
  
  postgres:
    container_name: k3i-postgres
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql
    networks:
      app-network:
        ipv4_address: 172.18.0.8
  
  pgadmin:
    container_name: k3i-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USERNAME}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    networks:
      - app-network
  
  meilisearch:
    container_name: k3i-meilisearch
    image: getmeili/meilisearch:v1.6
    ports:
      - 7700:7700
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - ./volumes/meilisearch:/meili_data
    networks:
      app-network:
        ipv4_address: 172.18.0.10

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16